services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - api-network
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    networks:
      - api-network
    environment:
      DATABASE_URL: 'postgresql://docker:docker@postgresql:5432/mydb?schema=public'

networks:
  api-network:
    driver: bridge

volumes:
  db:
